// Remediation API client — v1.6 GitHub MCP human-in-the-loop feature.
//
// Mirrors the backend RemediationDraftDetail Pydantic schema exactly.
// All requests go through the same BASE_URL / request() helper as infrapilot-api.ts.

// ---------------------------------------------------------------------------
// Client-side eligibility check — mirrors RemediationClassifier keyword rules
// so the "Draft PR" button is only shown when the backend would accept it.
// ---------------------------------------------------------------------------

// Mirrors backend RemediationClassifier._BLOCKED_KEYWORDS exactly.
// "roll back" (two words) is added to catch natural-language phrasing the
// agent produces even though the backend blocks the one-word "rollback".
const BLOCKED_KEYWORDS = [
  "rollback", "roll back", "revert",
  "secret", "credential",
  "kubectl", "helm",
  "migration", "migrate",
  "alter table", "drop table",
  "production mutation",
  "bq update", "bq mk",
  "rotate",
];

const SCHEMA_VALIDATION_KEYWORDS = [
  "schema", "validation", "validate", "compatibility",
  "pre-deploy", "predeploy", "pre_deploy",
];

/**
 * Returns true when the recommendation text would pass the backend
 * RemediationClassifier (not blocked, contains a schema-validation keyword).
 * Keeps the UI in sync with the backend so blocked actions never show the button.
 */
export function isRemediationEligible(recommendation: string): boolean {
  const text = recommendation.toLowerCase();
  if (BLOCKED_KEYWORDS.some((kw) => text.includes(kw))) return false;
  return SCHEMA_VALIDATION_KEYWORDS.some((kw) => text.includes(kw));
}

const BASE_URL: string =
  import.meta.env.VITE_INFRAPILOT_API_URL ?? "http://localhost:8000";

// ---------------------------------------------------------------------------
// Types — mirror backend app/schemas/remediation.py exactly
// ---------------------------------------------------------------------------

export type DraftStatus = "drafting" | "pr_created" | "failed";

/** One generated file in the draft PR. */
export interface FixFile {
  path: string;
  content: string;
  commit_message: string;
}

/** Full FixSpec as generated by the LLM and validated by policy. */
export interface FixSpec {
  branch_name: string;
  pr_title: string;
  pr_body: string;
  files: FixFile[];
  change_summary: string;
  test_plan: string;
  risk_notes: string;
}

/** Mirrors RemediationDraftDetail (all three GET/POST responses use this shape). */
export interface RemediationDraft {
  id: string;
  run_id: string;
  status: DraftStatus;
  selected_recommendation: string;
  fix_spec_json: FixSpec | null;
  target_repo: string;
  base_branch: string;
  branch_name: string | null;
  github_pr_url: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

// ---------------------------------------------------------------------------
// Internal fetch helper (same pattern as infrapilot-api.ts)
// ---------------------------------------------------------------------------

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json", ...((init?.headers as object) ?? {}) },
    ...init,
  });
  if (!res.ok) {
    let detail = `${res.status} ${res.statusText}`;
    try {
      const body = await res.json();
      if (typeof body?.detail === "string") {
        detail = body.detail;
      } else if (Array.isArray(body?.detail) && body.detail.length > 0) {
        detail = body.detail.map((d: { msg?: string }) => d.msg ?? JSON.stringify(d)).join("; ");
      }
    } catch {
      // body wasn't JSON — fall back to status text
    }
    throw new Error(detail);
  }
  return res.json() as Promise<T>;
}

// ---------------------------------------------------------------------------
// API functions
// ---------------------------------------------------------------------------

/**
 * POST /runs/{runId}/remediation-drafts
 *
 * Creates a new remediation draft for the given run and recommendation.
 * Returns immediately with status="drafting"; poll getRemediationDraft() until
 * status transitions to "pr_created" or "failed".
 *
 * Throws with a user-readable message on:
 *   400 — run not completed
 *   422 — recommendation blocked or service not eligible
 *   503 — GitHub token not configured
 */
export function createRemediationDraft(
  runId: string,
  selectedRecommendation: string,
): Promise<RemediationDraft> {
  return request<RemediationDraft>(`/runs/${runId}/remediation-drafts`, {
    method: "POST",
    body: JSON.stringify({ selected_recommendation: selectedRecommendation }),
  });
}

/**
 * GET /remediation-drafts/{draftId}
 *
 * Fetch a single draft by ID. Poll this until status !== "drafting".
 */
export function getRemediationDraft(draftId: string): Promise<RemediationDraft> {
  return request<RemediationDraft>(`/remediation-drafts/${draftId}`);
}

/**
 * GET /runs/{runId}/remediation-drafts
 *
 * List all drafts for a run, newest first.
 */
export function listRemediationDrafts(runId: string): Promise<RemediationDraft[]> {
  return request<RemediationDraft[]>(`/runs/${runId}/remediation-drafts`);
}
